users:
    user: ## Username
        displayname: "user"
        ## https://www.authelia.com/reference/guides/passwords/#passwords
        password: "hash"
        email: "authelia@authelia.com"
        groups:
            - "admin"
            - "dev"
