---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Закладки:

    - Github:
        - icon: github.png
          href: https://github.com/

    - Codeberg:
        - icon: codeberg.png
          href: https://codeberg.org/

    - Flathub:
        - icon: flathub.png
          href: https://flathub.org/

    - ARU:
        - icon: codeberg.png
          href: https://ventureo.codeberg.page/

    - Forum Sanohosting:
        - abbr: FS
          href: https://forum.samohosting.ru/


- Baxet Group:
    
   - SCOM:       
        - abbr: SC
          href: https://scom.do.indusov.net/accounts/details/310641
          
   - Justhost:       
        - abbr: JH
          href: http://justhost.ru/
   
   - Atlassian:       
        - abbr: AT
          href: https://home.atlassian.com/
   
   - Fresh Desk:       
        - abbr: FD
          href: https://baxet-support.freshdesk.com/
   
   - Abuse:       
        - abbr: AB
          href: https://abuse.do.indusov.net/
          
   - NB (сети):       
        - abbr: NB
          href: https://nb.do.indusov.net/ipam/prefixes/
   
   - BAPI (фин. операции):       
        - abbr: BA
          href: https://bapi.do.indusov.net/admin/
   
   - CMDB:       
        - abbr: CM
          href: https://cmdb.do.indusov.net/admin/
